[build]
builder = "NIXPACKS"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "gunicorn -k uvicorn.workers.UvicornWorker -b 0.0.0.0:$PORT app.main:app"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.multiRegionConfig]
[deploy.multiRegionConfig.us-west2]
numReplicas = 1