[build]
builder = "NIXPACKS"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "gunicorn -b 0.0.0.0:$PORT app:app --workers 1 --threads 4 --timeout 180 --preload"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
sleepApplication = false
